force-app/main/default/objects/Inventory_Transfer_Order__c/Inventory_Transfer_Order__c.object-meta.xml
<CustomObject>
    <label>Inventory Transfer Order</label>
    <nameField>
        <displayFormat>XFR-{0000000}</displayFormat>
        <label>Transfer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Transfer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Transfer_Order__c/fields/Destination_Location__c.field-meta.xml
<CustomField>
    <fullName>Destination_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Destination Location</label>
    <referenceTo>AcctSeedERP__Location__c</referenceTo>
    <relationshipLabel>Transfer Orders (This Destination)</relationshipLabel>
    <relationshipName>Inventory_Transfer_Orders_dest</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Transfer_Order__c/fields/Origin_Location__c.field-meta.xml
<CustomField>
    <fullName>Origin_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Origin Location</label>
    <referenceTo>AcctSeedERP__Location__c</referenceTo>
    <relationshipLabel>Inventory Transfer Orders (This Origin)</relationshipLabel>
    <relationshipName>Inventory_Transfer_Orders_orig</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Transfer_Order_Line__c/Inventory_Transfer_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Inventory Transfer Order Line</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Transfer Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Transfer_Order_Line__c/fields/Box_Count_Sent__c.field-meta.xml
<CustomField>
    <fullName>Box_Count_Sent__c</fullName>
    <formula>Quantity_Sent__c / Product__r.Case_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Box Count Sent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Transfer_Order_Line__c/fields/Inventory_Transfer_Order__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Transfer_Order__c</fullName>
    <label>Inventory Transfer Order</label>
    <referenceTo>Inventory_Transfer_Order__c</referenceTo>
    <relationshipLabel>Inventory Transfer Order Lines</relationshipLabel>
    <relationshipName>Inventory_Transfer_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inventory_Transfer_Order_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Transfer Order Lines</relationshipLabel>
    <relationshipName>Inventory_Transfer_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Transfer_Order_Line__c/fields/Quantity_Sent__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Sent__c</fullName>
    <label>Qty Sent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/gcInventoryTransferOrderPDF.cls
public without sharing class gcInventoryTransferOrderPDF {

    public gcInventoryTransferOrderPDF(ApexPages.StandardController c){
        init(c.getId());
    }

    public transient wrapTfr wrapTfr{get;set;}

    public class wrapTfr{
        public Inventory_Transfer_Order__c tfr{get;set;}
    }

    public void init(Id tfrId)
    {
        wrapTfr = new wrapTfr();
        wrapTfr.tfr = [
            SELECT Id,
                    Name,
                    Destination_Location__r.Name,
                    Destination_Location__r.AcctSeedERP__Warehouse__r.Name,
                    Origin_Location__r.Name,
                    Origin_Location__r.AcctSeedERP__Warehouse__r.Name,
                    //Destination_Warehouse__r.Name,
                    //Origin_Warehouse__r.Name,
                    CreatedDate,
                    (SELECT Id,
                            Name,
                            Product__c,
                            Product__r.GTIN_1__c,
                            Product__r.GTIN_2__c,
                            Product__r.Name,
                            Product__r.ProductCode,
                            Box_Count_Sent__c,
                            Quantity_Sent__c
                    FROM Inventory_Transfer_Order_Lines__r
                    ORDER BY Name)
            FROM Inventory_Transfer_Order__c 
            WHERE Id =: tfrId][0];
    }
}