force-app/main/default/objects/Pricing_Data__c/Pricing_Data__c.object-meta.xml
<CustomObject>
    <description>Custom object to store the pricing data sheet attributes</description>
    <label>Pricing Data</label>
    <nameField>
        <displayFormat>PD-{000}</displayFormat>
        <label>Pricing Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SKU_Price__c/SKU_Price__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Products and Pricing Data</description>
    <label>SKU Price</label>
    <nameField>
        <displayFormat>SKU-{000000}</displayFormat>
        <label>SKU Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SKU Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SKU_Price__c/fields/Pricing_Data__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Data__c</fullName>
    <label>Pricing Data</label>
    <referenceTo>Pricing_Data__c</referenceTo>
    <relationshipLabel>SKU Prices</relationshipLabel>
    <relationshipName>SKU_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SKU_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SKU Prices</relationshipLabel>
    <relationshipName>SKU_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/preventDuplicateSkuPriceHandlerTest.cls
@isTest
public class preventDuplicateSkuPriceHandlerTest {
    @isTest
    static void testDuplicateInsert() {
        Product2 prod1 = new Product2(Name='Test Product 1', IsActive=true);
        insert prod1;
        Pricing_Data__c pricingData = new Pricing_Data__c();
        insert pricingData;
        
        SKU_Price__c newSku = new SKU_Price__c(Product__c=prod1.Id, Pricing_Data__c=pricingData.Id);
        List<SKU_Price__c> newSkus = new List<SKU_Price__c>{newSku};
        insert newsku;
        
        SKU_Price__c duplicateSku = new SKU_Price__c(Product__c=prod1.Id, Pricing_Data__c=pricingData.Id);
        List<SKU_Price__c> duplicateSkus = new List<SKU_Price__c>{duplicateSku};
        
        Test.startTest();
        try{
           preventDuplicateSkuPriceHandler.preventDuplicateInsertOrUpdate(duplicateSkus);
            } catch (DmlException e) {
                System.assert(e.getMessage().contains('A combination of this Product and Pricing Data already exists'), e.getMessage());
            }
        Test.stopTest();
    }
}