force-app/main/default/objects/Pricing_Data__c/Pricing_Data__c.object-meta.xml
<CustomObject>
    <description>Custom object to store the pricing data sheet attributes</description>
    <label>Pricing Data</label>
    <nameField>
        <displayFormat>PD-{000}</displayFormat>
        <label>Pricing Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SKU_Price__c/SKU_Price__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Products and Pricing Data</description>
    <label>SKU Price</label>
    <nameField>
        <displayFormat>SKU-{000000}</displayFormat>
        <label>SKU Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SKU Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SKU_Price__c/fields/Pricing_Data__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Data__c</fullName>
    <label>Pricing Data</label>
    <referenceTo>Pricing_Data__c</referenceTo>
    <relationshipLabel>SKU Prices</relationshipLabel>
    <relationshipName>SKU_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SKU_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SKU Prices</relationshipLabel>
    <relationshipName>SKU_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/preventDuplicateSkuPriceHandler.cls
public without sharing class preventDuplicateSkuPriceHandler {
    
    public static void preventDuplicateInsertOrUpdate(List<SKU_Price__c> newSkus) {
        List<Id>    prod     = new List<Id>();
        List<Id> pricingData = new List<Id>();
        
        for(SKU_Price__c newSku : newSkus){
            prod.add(newSku.Product__c);
            pricingData.add(newSku.Pricing_Data__c);
        }
        
        List<SKU_Price__c> existingSKU = [SELECT Id, Product__c, Pricing_Data__c FROM SKU_Price__c WHERE Product__c IN: prod AND Pricing_Data__c IN:pricingData];
        
        if(existingSKU.size()>0){
            existingSKU[0].addError('A combination of this Product and Pricing Data already exists');
        }
    }
}