force-app/main/default/objects/My_Product__c/My_Product__c.object-meta.xml
<CustomObject>
    <description>Portal product line items</description>
    <label>My Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Product__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/My_Product__c/fields/My_Order__c.field-meta.xml
<CustomField>
    <fullName>My_Order__c</fullName>
    <label>My Order</label>
    <referenceTo>portal_my_order__c</referenceTo>
    <relationshipLabel>My Products</relationshipLabel>
    <relationshipName>My_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/My_Product__c/fields/Price_Per_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Item__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price Per Item</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/My_Product__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Price_Per_Item__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/portal_my_order__c/portal_my_order__c.object-meta.xml
<CustomObject>
    <label>My Order</label>
    <nameField>
        <label>My Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/portal_my_order__c/fields/Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/portal_my_order__c/fields/Must_Have_Date__c.field-meta.xml
<CustomField>
    <fullName>Must_Have_Date__c</fullName>
    <label>Must Have Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/portal_my_order__c/fields/Needs_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Needs_Approval_Date__c</fullName>
    <formula>Opportunity__r.CloseDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Needs Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/portal_my_order__c/fields/Production_Stage__c.field-meta.xml
<CustomField>
    <fullName>Production_Stage__c</fullName>
    <label>Production Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled for Production</fullName>
                <default>true</default>
                <label>Scheduled for Production</label>
            </value>
            <value>
                <fullName>Prepped for Print</fullName>
            </value>
            <value>
                <fullName>Printing in Progress</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Job Complete</fullName>
                <label>Order Complete</label>
            </value>
            <value>
                <fullName>Job Shipped</fullName>
                <label>Order Shipped</label>
            </value>
            <value>
                <fullName>Art Prepared for Print</fullName>
                <isActive>false</isActive>
                <label>Art Prepared for Print</label>
            </value>
            <value>
                <fullName>Garments Staged</fullName>
                <isActive>false</isActive>
                <label>Garments Staged</label>
            </value>
            <value>
                <fullName>Screens Prepared</fullName>
                <isActive>false</isActive>
                <label>Screens Prepared</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/portal_my_order__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote_Request</fullName>
                <default>true</default>
                <label>Quote Request</label>
            </value>
            <value>
                <fullName>Quote Ready</fullName>
            </value>
            <value>
                <fullName>Quote Approved</fullName>
            </value>
            <value>
                <fullName>Art Started</fullName>
            </value>
            <value>
                <fullName>Art Ready</fullName>
            </value>
            <value>
                <fullName>Art Approved</fullName>
            </value>
            <value>
                <fullName>Sizes Submitted</fullName>
            </value>
            <value>
                <fullName>Scheduled for Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/portal_my_order__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>My_Product__c.Total_Price__c</summarizedField>
    <summaryForeignKey>My_Product__c.My_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/portal_my_order__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/PortalSiteController.cls
public without sharing class PortalSiteController {
    
    @AuraEnabled(cacheable=true)
    public static List<portal_my_order__c> getMyOrders(string userId, string type){
        User userRecord = new User();
        String contactId = userId;
        if(!Test.isRunningTest()){
            // userRecord = [Select Id,Name,ContactId from user where Id =:userId LIMIT 1];
            // contactId = userRecord.ContactId;
            contactId = userId;
        }
        if(type == 'Pending'){
            return [SELECT Id, Name,Stage__c,Balance_Due__c FROM portal_my_order__c where OwnerId  =: contactId AND 
                    (Stage__c  in ('Quote Ready', 'Art Ready') OR Balance_Due__c > 0.0) order by CreatedDate Desc];
        }
        else if(type == 'Completed'){
            return [SELECT Id, Name,Stage__c,Balance_Due__c,Total_Price__c,Tracking_Number__c,CreatedDate FROM portal_my_order__c 
                    where OwnerId  =: contactId AND Production_Stage__c = 'Job Shipped' AND (Balance_Due__c > 0.0 OR Balance_Due__c = null OR Balance_Due__c = 0) 
                    order by CreatedDate DESC];
        }
    
        else if(type == 'Invoice'){
        return [SELECT Id, Name,Stage__c,Balance_Due__c,Total_Price__c,Tracking_Number__c,CreatedDate FROM portal_my_order__c 
                where OwnerId  =: contactId AND (Balance_Due__c > 0.0 ) 
                order by CreatedDate DESC];
        }
        else{
            return [SELECT Id, Name,Stage__c,Needs_Approval_Date__c,Must_Have_Date__c,Balance_Due__c,Total_Price__c,CreatedDate FROM portal_my_order__c 
            where OwnerId  =: contactId AND (Production_Stage__c  != 'Job Shipped' OR Balance_Due__c > 0.0) order by CreatedDate Desc];
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<My_Product__c> getOrderProds(string orderId){
        return [SELECT Id, Name,Color__c,Quantity__c,Price_Per_Item__c,Total_Price__c FROM My_Product__c where My_Order__c =: orderId order by CreatedDate Desc];
    }
}