force-app/main/default/objects/Community_Guidance_System__c/Community_Guidance_System__c.object-meta.xml
<CustomObject>
    <label>Community Guidance System</label>
    <nameField>
        <label>Community Guidance System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Guidance Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Guidance_System__c/fields/is_First_Message__c.field-meta.xml
<CustomField>
    <fullName>is_First_Message__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is First Message</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Guidance_System__c/fields/is_Last_Message__c.field-meta.xml
<CustomField>
    <fullName>is_Last_Message__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Last Message</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Guidance_System__c/fields/Main_Message__c.field-meta.xml
<CustomField>
    <fullName>Main_Message__c</fullName>
    <label>Main Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Guidance_System__c/fields/Message_No__c.field-meta.xml
<CustomField>
    <fullName>Message_No__c</fullName>
    <label>Message No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GuidanceSystemControllerTest.cls
@isTest
public class GuidanceSystemControllerTest {
    
    @TestSetup
    public static void init() {
    	Community_Guidance_System__c cgs = new Community_Guidance_System__c();
        cgs.is_First_Message__c = true;
        cgs.is_Last_Message__c = false;
        cgs.Main_Message__c = 'test message';
        cgs.Message_No__c = 1;
        cgs.Page_Number__c = 1;
        cgs.Title__c = 'test title';
        
        insert cgs;
                
    }
    
    @isTest 
    public static void testArtApprevedCase() {
        Test.startTest();
        GuidanceSystemController.findAll();
        GuidanceSystemController.hideWalkthrough();
        Test.stopTest();
    }

}