force-app/main/default/objects/Community_Guidance_System__c/Community_Guidance_System__c.object-meta.xml
<CustomObject>
    <label>Community Guidance System</label>
    <nameField>
        <label>Community Guidance System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Guidance Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Guidance_System__c/fields/is_First_Message__c.field-meta.xml
<CustomField>
    <fullName>is_First_Message__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is First Message</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Guidance_System__c/fields/is_Last_Message__c.field-meta.xml
<CustomField>
    <fullName>is_Last_Message__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Last Message</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Guidance_System__c/fields/Main_Message__c.field-meta.xml
<CustomField>
    <fullName>Main_Message__c</fullName>
    <label>Main Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Guidance_System__c/fields/Message_No__c.field-meta.xml
<CustomField>
    <fullName>Message_No__c</fullName>
    <label>Message No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GuidanceSystemController.cls
public without sharing class GuidanceSystemController {
    
    @AuraEnabled
    public static List<Community_Guidance_System__c> findAll() {
        List<Community_Guidance_System__c> CGSList = [SELECT Id, Name, is_First_Message__c, is_Last_Message__c, Main_Message__c, Message_No__c, Page_Number__c, Title__c 
                                                      FROM Community_Guidance_System__c ];
        Boolean walkthrough = [SELECT Id, Name, Walkthrough_Guide__c FROM User WHERE Id = :UserInfo.getUserId()].Walkthrough_Guide__c;
        if(walkthrough){
            return CGSList;
        }
        return null;
        
    }
    
    @AuraEnabled
    public static void hideWalkthrough() {
        List<User> userList = [SELECT Id, Name, Walkthrough_Guide__c FROM User WHERE Id = :UserInfo.getUserId()];
        User userObj = new User();
        if(userList.size()>0){
            userObj = userList[0];
            userObj.Walkthrough_Guide__c = false;
        }
        update userObj;
        
    }
    
}